### ISSUE TITLE
err

### ISSUE THREAD

**Issue by Egida** [forkyyy/http-browser#3]
`TypeError [ERR_INVALID_ARG_TYPE]: The "secureOptions" argument must be of type number. Received type string ('SSL_OP_ALL')
    at new SecureContext (node:_tls_common:94:5)
    at Object.createSecureContext (node:_tls_common:114:13)
    at Object.connect (node:_tls_wrap:1621:48)
    at Object.createConnection (/home/admin/http-browser/browser/flooder.js:139:46)
    at Object.connect (node:internal/http2/core:3268:22)
    at ClientRequest.<anonymous> (/home/admin/http-browser/browser/flooder.js:138:39)
    at ClientRequest.emit (node:events:526:28)
    at Socket.socketOnData (node:_http_client:522:11)
    at Socket.emit (node:events:526:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  code: 'ERR_INVALID_ARG_TYPE'
}`
How to fix this?

**Comment by iLaravel** [comment]
fixed in: https://github.com/iLaravel/HTTP-BROWSER

if you find an error, create a issues

**Comment by Egida** [comment]
> fixed in: https://github.com/iLaravel/HTTP-BROWSER
> 
> if you find an error, create a issues

and what is the fix for commenting the code?

**Comment by iLaravel** [comment]
Fully fixed in: https://github.com/NekoLoliOwO/http-browser

This script should be work without errors, try it

**Comment by Egida** [comment]
> Fully fixed in: https://github.com/NekoLoliOwO/http-browser
> 
> This script should be work without errors, try it

no work

**Comment by iLaravel** [comment]
> > Fully fixed in: https://github.com/NekoLoliOwO/http-browser
> > This script should be work without errors, try it
> 
> no work

pm me on telegram: lrvlcde

**Comment by forkyyy** [comment]
Issue is solved, closed now.

**Comment by Egida** [comment]
who solved the problem?
